### ISSUE TITLE
The app crush every time after the latest update 7/26

### ISSUE THREAD

**Issue by JKawmi** [ferasm/reddhub#312] opened 2015-07-26 09:45 UTC
However, just fixed it by uninstalling and installing it again

I guess it's related to previous auto signing in ? because it crushes whenever it loads my subreddits

**Comment by dumptruckjon** [comment] 2015-07-26 15:31
fixed.  thanks for reporting!  duplicate of https://github.com/ferasm/reddhub/issues/311 and https://github.com/ferasm/reddhub/issues/310

**Closed as completed by dumptruckjon** 2015-07-26 15:31 UTC
