### ISSUE TITLE
List of subreddits can display all.

### ISSUE THREAD

**Issue by ReddhubApp** [ferasm/reddhub#331] opened 2015-08-17 09:37 UTC
There are two items in my list that can't display, there are back of windows Phone menú of options, I can ser it make scroll but I can't click it. Please fix it, thaks

**Comment by JDOfTheNorth** [comment] 2015-08-23 23:06
Dupe of https://github.com/ferasm/reddhub/issues/329.

**Closed as completed by JDOfTheNorth** 2015-08-23 23:06 UTC
